{% set name = "imgviz" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01efdfb4295040b07bb8d83c795b527083547916cb4914f1a370c511f060c380

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib-base
    - numpy
    - pillow >=5.3.0
    - pyyaml
    # contained in [all]
    - pyglet
    - scikit-image
    - scikit-learn

test:
  imports:
    - imgviz

about:
  home: https://github.com/wkentaro/imgviz
  # Upstream asked for clarification:
  # https://github.com/wkentaro/imgviz/issues/11
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Image Visualization Tools

extra:
  recipe-maintainers:
    - hmaarrfk
    - wkentaro
